            <!--end of div id="bodySize" & id="background" which are in the header -->
    	    </div>
    	</div>

    	<div id="footerSpacer"></div>

        <footer>

            <div class="container">
                <div class="row">

                    <div class="col-xs-12 col-sm-3">
                        <a href="http://www.ece.fr" title="ECE Paris Engineering School">
                            <img alt="ECE Paris logo" id="logo_ECE" src="/assets/img/logo_ECE.png" /></a>
                    </div>
                    <div class="col-xs-12 col-sm-6" id="text">
                        <p class="col-xs-12" id="title" title="ECE Heal Management System"><a href="#">ECE Health Management System</a></p>
                        <p class="col-xs-12">© 2013, All rights reserved. ECEHMS is a project of ECE Paris. <a href="/index/privacy">Privacy and Terms</a><p>
                    </div>
            	    
                    <div class="footer-links col-xs-12 col-sm-3">
                        <div class="row col-xs-12 pull-left">
                            <a href="https://twitter.com/">
                                <img alt="T" class="socialicon" src="/assets/img/sn/64x64/twitter.png" />Twitter</a>
                        </div>
                        <div class="row col-xs-12 pull-left">
                            <a href="/index/rss">
                                <img alt="R" class="socialicon" src="/assets/img/sn/64x64/rss.png" />RSS</a>
                        </div>
            	    </div>
                </div>
            </div>
            
    	</footer>

    	<!-- Placed at the end of the document so that the pages load faster -->

            <!-- For LESS files -->
            <script type="text/javascript">
                less = {
                    env: "development", // or "production"
                    async: false,       // load imports async
                    fileAsync: false,   // load imports async when in a page under a file protocol
                    poll: 1000,         // when in watch mode, time in ms between polls
                    functions: {},      // user functions, keyed by name
                    dumpLineNumbers: "comments", // or "mediaQuery" or "all"
                    relativeUrls: false,// whether to adjust url's to be relative if false, url's are already relative to the entry less file
                    rootpath: ":/a.com/"// a path to add on to the start of every url resource
                };
            </script>

            <!-- For JavaScript -->
            <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
            <script src="/assets/js/bootstrap.min.js"></script>
            <script src="/assets/js/less.js" type="text/javascript"></script>
            <script src="/assets/js/scrollingScript.js" type="text/javascript"></script>
            <script src="/assets/js/minHeight.js" type="text/javascript"></script>
            <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
            <script src="/assets/js/map.js"></script>
	    <script src="/assets/js/popup.js"></script>

     </body>
</html>
