<section>

    <div class="section-container">
        <div id="addUpdateProfile">
            <h1 class="margin-top">update</h1>

            <div id="updateAdd" class="card margin-top">

                The update has been send.<br />
                <br />
                <a href="/profile/index">
                    <button class="btn btn-primary"
                            id="sendButton"
                            type="button">
                        Return to dashboard
                    </button>
                </a>
            </div>

        </div>
    </div>
</section>