<section>

    <div class="container">
        <p id="instruction-signin">
            Consult your personal index card to reach at any time all your document concerning your examinations and medical meeting. You have real time access to all comments of you doctors.
        </p>
    </div>

    <div class="errorSignin">
        <?php if (isset($isRegistered) && $isRegistered == false): ?>
        <p>You are not connected: check your email and password !</p>
        <?php endif; ?>
    </div>

    <div id="signIn" class="form-horizontal signup-form" role="form" >

        <form   action="/members/signin"
                class="login"
                method="post"
                name="formSign"
                onsubmit="return validateFormSignIn()"
            >

            <h2>SIGN IN</h2>

            <div class="form-group" id="emailDiv">

                <label for="email" class="col-sm-4 control-label">Email</label>
                <div class="col-sm-8">

                    <input  class="form-control"
                            id="email"
                            maxlength="30"
                            name="email"
                            onblur="return hideHelp(this.name)"
                            onfocus="return showHelp(this.name)"
                            placeholder="Email"
                            size="30"
                            type="text"
                        />
                </div>
            </div>

            <div class="form-group" id="passwordDiv">
                <label for="password" class="col-sm-4 control-label">Password</label>
                <div class="col-sm-8">

                    <input  class="form-control"
                            id="password"
                            name="password"
                            onblur="return hideHelp(this.name)"
                            onfocus="return showHelp(this.name)"
                            placeholder="Password"
                            type="password"
                        />
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <button id="loginButton" type="submit" class="btn btn-primary pull-right">Sign in</button>
                </div>
            </div>

        </form>
    </div>
</section>


