<html>
<head>
    <link rel="stylesheet" href="/assets/CSS/styleMembers.css"/>
</head>
<body class="wall">
<section class="membersList">
    <h1>GET RSS</h1>

    <form method="post" action="/index/rss">
        <div>
            <label for="nbMember">Email: </label>
            <input type="text" name="pseudoMember" id="pseudoMember" value="">
            <button type="submit" id="showListButton">SHOW</button>
        </div>

    </form>
</section>
</body>
</html>