<section>

    <div class="section-container">
        <h1 class="margin-top">
            privacy and terms
        </h1>

        <div class="card margin-top" id="privacy">
            <h3>What information do we collect?</h3>
            <p>
                 We collect information from you when you register on our site.<br />
                 <br />
                 When ordering or registering on our site, as appropriate, you may be asked to enter your: name or e-mail address.<br />
            </p>
            <h3>How do we protect your information?</h3>
            <p>
                We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.<br />
            </p>
            <h3>Do we use cookies?</h3>
            <p>Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information.<br />
            </p>
            <h3>Do we disclose any information to outside parties?</h3>
            <p>
                We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.<br />
            </p>
            <h3>Online Privacy Policy Only</h3>
            <p>
                This online privacy policy applies only to information collected through our website and not to information collected offline.<br />
            </p>
            <h3>Your Consent</h3>
            <p>
                By using our site, you consent to our web site privacy policy.<br />
            </p>
            <h3>Changes to our Privacy Policy</h3>
            <p>
                If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. <br />
                <br />
                This policy was last modified on 15/12/2013 <br />
            </p>
        </div>
        <br />
        <br />

    </div>
</section>




